apiVersion: v1
kind: ConfigMap
metadata:
  name: vproapp-config
  namespace: prodproject
data:
  application.properties: |
    #JDBC Configutation for Database Connection
    jdbc.driverClassName=com.mysql.jdbc.Driver
    jdbc.url=jdbc:mysql://db-svc:3306/accounts?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    jdbc.username=${DB_USER}
    jdbc.password=${DB_PASSWORD}

    #Memcached Configuration For Active and StandBy Host
    #For Active Host
    memcached.active.host=mc-svc
    memcached.active.port=11211
    #For StandBy Host
    memcached.standBy.host=mc-svc
    memcached.standBy.port=11211

    #RabbitMQ Configuration
    rabbitmq.address=rmq-svc
    rabbitmq.port=5672
    rabbitmq.username=${RABBITMQ_USER}
    rabbitmq.password=${RABBITMQ_PASSWORD}

    #Elasticesearch Configuration
    elasticsearch.host=elasticsearch-service
    elasticsearch.port=9300
    elasticsearch.cluster=vprofile
    elasticsearch.node=vprofilenode
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: prodproject
data:
  vproapp.conf: |
    upstream vproapp {
        server app-svc:8080;
    }

    server {
        listen 80;
        
        location / {
            proxy_pass http://vproapp;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: prodproject
data:
  rabbitmq.conf: |
    loopback_users = none
    listeners.tcp.default = 5672
    management.tcp.port = 15672
